#!/usr/bin/env python3
"""
Generate watermarked PDFs from markdown files
"""

import os
import sys
import json
import subprocess
from datetime import datetime
from pathlib import Path

# Add scripts directory to path to import watermark module
sys.path.append(str(Path(__file__).parent))
from watermark import add_watermark_to_pdf

def convert_md_to_pdf(md_path, output_dir):
    """Convert markdown to PDF using pandoc"""
    md_path = Path(md_path)
    output_dir = Path(output_dir)
    
    # Create output directory
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate PDF filename
    pdf_filename = md_path.with_suffix('.pdf').name
    pdf_path = output_dir / pdf_filename
    
    cmd = [
        'pandoc', str(md_path),
        '-o', str(pdf_path),
        '--pdf-engine=xelatex',
        '-V', 'geometry:margin=1in',
        '-V', 'fontsize=11pt',
        '--toc', '--toc-depth=3',
        '--standalone'
    ]
    
    result = subprocess.run(cmd, capture_output=True, text=True)
    return pdf_path if result.returncode == 0 else None

def main():
    # Get files from first argument or environment
    if len(sys.argv) > 1:
        files_json = sys.argv[1]
    else:
        files_json = os.environ.get('FILES_JSON', '[]')
    
    try:
        files_to_process = json.loads(files_json)
    except:
        print("Error parsing JSON file list")
        sys.exit(1)
    
    if not files_to_process:
        print("No files to process")
        print("pdf_count=0")
        return
    
    # Generate watermark text
    actor = os.environ.get('GITHUB_ACTOR', 'unknown-user')
    timestamp = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
    
    # Custom watermark or default
    custom_watermark = os.environ.get('WATERMARK_TEXT', '')
    if custom_watermark:
        watermark_text = custom_watermark
    else:
        watermark_text = f"Generated by {actor} on {timestamp}"
    
    print(f"Processing {len(files_to_process)} file(s)")
    print(f"Watermark: {watermark_text}")
    
    generated_count = 0
    output_dir = Path('generated-pdfs')
    
    for md_file in files_to_process:
        if not os.path.isfile(md_file):
            print(f"File not found: {md_file}")
            continue
        
        print(f"\nProcessing: {md_file}")
        
        # Step 1: Convert to PDF
        temp_pdf = convert_md_to_pdf(md_file, output_dir)
        if not temp_pdf:
            print(f"✗ Pandoc conversion failed")
            continue
        
        # Step 2: Add watermark
        watermarked_pdf = temp_pdf.with_name(f"wm_{temp_pdf.name}")
        try:
            add_watermark_to_pdf(str(temp_pdf), str(watermarked_pdf), watermark_text)
            
            # Replace original with watermarked version
            temp_pdf.unlink()
            watermarked_pdf.rename(temp_pdf)
            
            print(f"✓ Generated: {temp_pdf}")
            generated_count += 1
        except Exception as e:
            print(f"✗ Watermarking failed: {e}")
            if temp_pdf.exists():
                temp_pdf.unlink()
    
    # Set output for GitHub Actions
    print(f"\nGenerated {generated_count} PDF(s)")
    with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
        f.write(f"pdf_count={generated_count}\n")

if __name__ == '__main__':
    main()
