#!/usr/bin/env python3
"""
Generate PDFs from markdown files with watermarks
"""

import os
import json
import subprocess
import tempfile
from datetime import datetime
from scripts.watermark import add_watermark_to_pdf

def main():
    # Get environment variables
    files_json = os.environ.get('FILES_JSON', '[]')
    actor = os.environ.get('ACTOR', 'Unknown')
    timestamp = os.environ.get('TIMESTAMP', datetime.now().isoformat())
    custom_watermark = os.environ.get('CUSTOM_WATERMARK', '')
    
    # Parse the timestamp
    try:
        dt = datetime.fromisoformat(timestamp.replace('Z', '+00:00'))
        formatted_time = dt.strftime("%Y-%m-%d %H:%M:%S")
    except:
        formatted_time = timestamp
    
    # Create watermark text
    if custom_watermark:
        watermark_text = custom_watermark
    else:
        watermark_text = f"Generated by {actor} on {formatted_time}"
    
    print(f"Watermark: {watermark_text}")
    
    # Parse files list
    try:
        files_to_process = json.loads(files_json)
    except json.JSONDecodeError:
        print("Error parsing files JSON")
        files_to_process = []
    
    if not files_to_process:
        print("No files to process")
        return
    
    print(f"Processing {len(files_to_process)} files...")
    
    # Ensure output directory exists
    os.makedirs('generated-pdfs', exist_ok=True)
    
    # Process each file
    for md_file in files_to_process:
        if not os.path.exists(md_file):
            print(f"File not found: {md_file}")
            continue
            
        print(f"Converting: {md_file}")
        
        # Create PDF filename (preserve directory structure)
        if md_file.startswith('doc/'):
            pdf_name = md_file[4:]  # Remove 'doc/' prefix
        else:
            pdf_name = os.path.basename(md_file)
        
        pdf_name = pdf_name.replace('.md', '.pdf')
        pdf_path = os.path.join('generated-pdfs', pdf_name)
        
        # Create directory if needed
        os.makedirs(os.path.dirname(pdf_path), exist_ok=True)
        
        # Convert markdown to PDF using pandoc
        try:
            # Create a temporary PDF first
            with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp_file:
                temp_pdf = tmp_file.name
            
            # Convert using pandoc
            cmd = [
                'pandoc', md_file,
                '-o', temp_pdf,
                '--pdf-engine=xelatex',
                '-V', 'geometry:margin=1in',
                '-V', 'fontsize=12pt',
                '--template', 'scripts/template.tex' if os.path.exists('scripts/template.tex') else None
            ]
            
            # Remove None values
            cmd = [c for c in cmd if c is not None]
            
            result = subprocess.run(cmd, capture_output=True, text=True)
            
            if result.returncode != 0:
                print(f"Pandoc error for {md_file}: {result.stderr}")
                continue
            
            # Add watermark
            add_watermark_to_pdf(temp_pdf, pdf_path, watermark_text)
            
            print(f"✓ Generated: {pdf_path}")
            
            # Clean up temp file
            os.unlink(temp_pdf)
            
        except Exception as e:
            print(f"Error processing {md_file}: {str(e)}")
            continue
    
    print("PDF generation complete!")

if __name__ == "__main__":
    main()
