#!/usr/bin/env python3
"""
Generate PDFs from markdown files with watermarks
Outputs PDFs to the same directory as the source .md files
"""

import os
import json
import subprocess
import tempfile
import sys
from datetime import datetime
from scripts.watermark import add_watermark_to_pdf

def get_files_to_process():
    """Determine which .md files to process based on trigger type"""
    event_name = os.environ.get('EVENT_NAME', '')
    scope = os.environ.get('GENERATION_SCOPE', '')
    specific_files = os.environ.get('SPECIFIC_FILES', '')
    changed_files_json = os.environ.get('CHANGED_FILES_JSON', '[]')
    
    files_to_process = []
    
    if event_name == 'workflow_dispatch':
        # Manual trigger
        if scope == 'all':
            # Find all .md files in doc/ directory
            for root, dirs, files in os.walk('doc'):
                for file in files:
                    if file.endswith('.md'):
                        files_to_process.append(os.path.join(root, file))
        elif scope == 'specific' and specific_files:
            # Process specific files
            for file_path in specific_files.split(','):
                file_path = file_path.strip()
                if file_path.endswith('.md') and os.path.exists(file_path):
                    files_to_process.append(file_path)
    else:
        # Push event - process changed files
        try:
            changed_files = json.loads(changed_files_json)
            files_to_process = [f for f in changed_files if f.endswith('.md') and os.path.exists(f)]
        except json.JSONDecodeError:
            print("Error parsing changed files JSON")
            files_to_process = []
    
    return files_to_process

def main():
    # Get environment variables
    actor = os.environ.get('ACTOR', 'Unknown')
    timestamp = os.environ.get('TIMESTAMP', datetime.now().isoformat())
    custom_watermark = os.environ.get('CUSTOM_WATERMARK', '')
    
    # Parse the timestamp
    try:
        dt = datetime.fromisoformat(timestamp.replace('Z', '+00:00'))
        formatted_time = dt.strftime("%Y-%m-%d %H:%M:%S UTC")
    except:
        formatted_time = timestamp
    
    # Create watermark text
    if custom_watermark:
        watermark_text = custom_watermark
    else:
        watermark_text = f"Generated by {actor} on {formatted_time}"
    
    print(f"📝 Watermark: {watermark_text}")
    
    # Get files to process
    files_to_process = get_files_to_process()
    
    if not files_to_process:
        print("ℹ️  No files to process")
        return
    
    print(f"🔄 Processing {len(files_to_process)} file(s)...")
    
    # Track generated PDFs
    generated_pdfs = []
    
    # Process each file
    for md_file in files_to_process:
        if not os.path.exists(md_file):
            print(f"⚠️  File not found: {md_file}")
            continue
            
        print(f"📄 Converting: {md_file}")
        
        # Create PDF filename (same directory, same base name, .pdf extension)
        pdf_file = md_file.replace('.md', '.pdf')
        
        try:
            # Create a temporary PDF first
            with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp_file:
                temp_pdf = tmp_file.name
            
            # Convert using pandoc
            cmd = [
                'pandoc', md_file,
                '-o', temp_pdf,
                '--pdf-engine=xelatex',
                '-V', 'geometry:margin=1in',
                '-V', 'fontsize=11pt',
                '-V', 'mainfont="DejaVu Serif"',
                '--toc',  # Add table of contents
                '--toc-depth=3'
            ]
            
            # Add metadata if available
            if os.path.exists('scripts/template.tex'):
                cmd.extend(['--template', 'scripts/template.tex'])
            
            result = subprocess.run(cmd, capture_output=True, text=True)
            
            if result.returncode != 0:
                print(f"❌ Pandoc error for {md_file}:")
                print(f"   {result.stderr}")
                continue
            
            # Add watermark to the generated PDF
            add_watermark_to_pdf(temp_pdf, pdf_file, watermark_text)
            
            # Clean up temp file
            os.unlink(temp_pdf)
            
            # Track generated PDF
            generated_pdfs.append(pdf_file)
            print(f"✅ Generated: {pdf_file}")
            
        except Exception as e:
            print(f"❌ Error processing {md_file}: {str(e)}")
            continue
    
    # Write list of generated PDFs to file for git commit step
    with open('/tmp/generated_pdfs.txt', 'w') as f:
        for pdf in generated_pdfs:
            f.write(pdf + '\n')
    
    print(f"🎉 PDF generation complete! Generated {len(generated_pdfs)} PDF(s).")

if __name__ == "__main__":
    main()
